num1 = input('Enter first number: ')  
num2 = input('Enter second number: ')  
sum = float(num1) + float(num2) 
min = float(num1) - float(num2)    
mul = float(num1) * float(num2)   
div = float(num1) / float(num2)  
print('The sum is',sum)   
print('The subtraction is',min)
print('The multiplication is',mul)  
print('The division is',div)  
